---
- vars_files:
  - vars.yml

  hosts: localhost

  tasks:

  - nova_compute:
      image_name: "{{ ubuntu_img_name }}"
      key_name: "{{ pubkey_name }}"
      name:  "{{ ubuntu_instance_name }}"
      # floating ip setting depends on features of your OpenStack installation":
      floating_ip_pools: [public]

      auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
      login_username: "{{ lookup('env', 'OS_USERNAME') }}"
      login_password: "{{ lookup('env', 'OS_PASSWORD') }}"
      login_tenant_name: "{{ lookup('env', 'OS_TENANT_ID') }}"

  - nova_compute:
      name: "{{ centos_instance_name }}"
      image_name: "{{ centos_img_name }}"
      key_name: "{{ pubkey_name }}"
      # floating ip setting depends on features of your OpenStack installation":
      floating_ip_pools: [public]

      auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
      login_username: "{{ lookup('env', 'OS_USERNAME') }}"
      login_password: "{{ lookup('env', 'OS_PASSWORD') }}"
      login_tenant_name: "{{ lookup('env', 'OS_TENANT_ID') }}"

